site_name: TxDUG
site_url: https://txdug.org
repo_url: https://github.com/TxDUG/txdug.github.io
repo_name: txdug.org
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: blue
    accent: deep orange
  favicon: ""
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
plugins: []
extra_css:
  - extra.css
